matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      language: node_js
      node_js: "12"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true
        - CSC_IDENTITY_AUTO_DISCOVERY=false

    - os: linux
      services: docker
      language: generic
      node_js: "12"
      env:
        - ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true

cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder

script:
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      ENVS=`env | grep -iE '(DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_)' | sed -n '/^[^\t]/s/=.*//p' | sed '/^$/d' | sed 's/^/-e /g' | tr '\n' ' '`
      docker run $ENVS --rm \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "node -v && npm ci && npm run cilinux"
    else
      npm run cidarwin
    fi
  # - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  # - git config --local user.name "Gamer4life1"
  # - git config --local user.email "lpuvilla0001@mymail.lausd.net"
  # - git tag $TRAVIS_TAG

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

# before_deploy:
#   - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#   - git config --local user.name "Gamer4life1"
#   - git config --local user.email "lpuvilla0001@mymail.lausd.net"
#   - git tag $TRAVIS_TAG

deploy:
  provider: releases
  # ⋮
  edge: true
  api_key: $GH_TOKEN
  file:
    - dist/Helioss-Launcher-setup-2.0.0-release.exe
    - dist/Helioss-Launcher-setup-2.0.0-release.AppImage
    - dist/Helioss-Launcher-setup-2.0.0-release.dmg
    - dist/Helioss-Launcher-setup-2.0.0-release.exe.blockmap
    - dist/latest-mac.yml
    - dist/latest-linux.yml
    - dist/latest.yml
  skip_cleanup: true
  draft: true
  overwrite: false
  on:
    tags: true